const gtef_collection = require('../../models/gtef');
require('dotenv').config();

module.exports = async (req, res) => {
  const {
    ref,
    prefix,
    firstName,
    middleName,
    lastName,
    dob,
    gender,
    mobCode,
    mobile,
    email,
    choosingNotToStudyInYourHomeCountry,
    whyChoosenToStudyInAustralia,
    whyChoosenToStudyInSignit,
    whatDoYouKnowAboutCourse,
    explainWhyChoosenToChange,
    providedCertifiedExplainWhy,
    firstYearCostperPerson,
    firstYearNumberOfPeople,
    firstYearTotalCost,
    applicantCostperPerson,
    applicantNumberOfPeople,
    applicantTotalCost,
    partnerCostperPerson,
    partnerNumberOfPeople,
    partnerTotalCost,
    childCostperPerson,
    childNumberOfPeople,
    childTotalCost,
    airfaresCostperPerson,
    airfaresNumberOfPeople,
    airfaresTotalCost,
    selfProvide,
    selfCertified,
    sponserProvide,
    sponcerCertified,
    loanProvide,
    loanCertified,
    otherProvide,
    otherCertified,
    genuineStudent,
    declarationPrefix,
    declarationFirstName,
    declarationMiddleName,
    declarationLastName,
    declarationDate,
  } = req.body.formData;

  const {
    signatureImage,
    changingAreaOfStudy,
    providedCertifiedCopyOfEvidence,
  } = req.body;

  const newgtef = new gtef_collection({
    ref,
    name: {
      prefix,
      firstName,
      middleName,
      lastName,
    },
    dob,
    gender,
    mob: {
      mobCode,
      mobile,
    },
    email,
    choosingNotToStudyInYourHomeCountry,
    whyChoosenToStudyInAustralia,
    whyChoosenToStudyInSignit,
    whatDoYouKnowAboutCourse,
    changingAreaOfStudy,
    explainWhyChoosenToChange,
    providedCertifiedCopyOfEvidence,
    providedCertifiedExplainWhy,
    firstYearCostperPerson,
    firstYearNumberOfPeople,
    firstYearTotalCost,
    applicantCostperPerson,
    applicantNumberOfPeople,
    applicantTotalCost,
    partnerCostperPerson,
    partnerNumberOfPeople,
    partnerTotalCost,
    childCostperPerson,
    childNumberOfPeople,
    childTotalCost,
    airfaresCostperPerson,
    airfaresNumberOfPeople,
    airfaresTotalCost,
    selfProvide,
    selfCertified,
    sponserProvide,
    sponcerCertified,
    loanProvide,
    loanCertified,
    otherProvide,
    otherCertified,
    genuineStudent,
    declarationPrefix,
    declarationFirstName,
    declarationMiddleName,
    declarationLastName,
    declarationDate,
    signatureImage,
  });
  gtef_collection
    .insertMany(newgtef)
    .then((result) => {
      res.send({ Status: 'Success', result: result });
    })
    .catch((e) => {
      console.log('Serverside error', e);
    });
};
